// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: proto/grpcfs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RPC Helper Context - Define as needed
type RPCContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GatewayId   string `protobuf:"bytes,1,opt,name=GatewayId,proto3" json:"GatewayId,omitempty"`
	AccessToken string `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	AgentId     string `protobuf:"bytes,3,opt,name=AgentId,proto3" json:"AgentId,omitempty"`
}

func (x *RPCContext) Reset() {
	*x = RPCContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCContext) ProtoMessage() {}

func (x *RPCContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCContext.ProtoReflect.Descriptor instead.
func (*RPCContext) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{0}
}

func (x *RPCContext) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *RPCContext) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RPCContext) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Primitive
type OpContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuseId uint64 `protobuf:"varint,1,opt,name=FuseId,proto3" json:"FuseId,omitempty"`
	Pid    uint64 `protobuf:"varint,2,opt,name=Pid,proto3" json:"Pid,omitempty"`
	Uid    uint64 `protobuf:"varint,3,opt,name=Uid,proto3" json:"Uid,omitempty"`
}

func (x *OpContext) Reset() {
	*x = OpContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpContext) ProtoMessage() {}

func (x *OpContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpContext.ProtoReflect.Descriptor instead.
func (*OpContext) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{1}
}

func (x *OpContext) GetFuseId() uint64 {
	if x != nil {
		return x.FuseId
	}
	return 0
}

func (x *OpContext) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *OpContext) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// Toplevel
type StatFs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockSize       uint32 `protobuf:"varint,1,opt,name=BlockSize,proto3" json:"BlockSize,omitempty"`
	Blocks          uint64 `protobuf:"varint,2,opt,name=Blocks,proto3" json:"Blocks,omitempty"`
	BlocksFree      uint64 `protobuf:"varint,3,opt,name=BlocksFree,proto3" json:"BlocksFree,omitempty"`
	BlocksAvailable uint64 `protobuf:"varint,4,opt,name=BlocksAvailable,proto3" json:"BlocksAvailable,omitempty"`
	IoSize          uint32 `protobuf:"varint,5,opt,name=IoSize,proto3" json:"IoSize,omitempty"`
	Inodes          uint64 `protobuf:"varint,6,opt,name=Inodes,proto3" json:"Inodes,omitempty"`
	InodesFree      uint64 `protobuf:"varint,7,opt,name=InodesFree,proto3" json:"InodesFree,omitempty"`
}

func (x *StatFs) Reset() {
	*x = StatFs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatFs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFs) ProtoMessage() {}

func (x *StatFs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFs.ProtoReflect.Descriptor instead.
func (*StatFs) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{2}
}

func (x *StatFs) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *StatFs) GetBlocks() uint64 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *StatFs) GetBlocksFree() uint64 {
	if x != nil {
		return x.BlocksFree
	}
	return 0
}

func (x *StatFs) GetBlocksAvailable() uint64 {
	if x != nil {
		return x.BlocksAvailable
	}
	return 0
}

func (x *StatFs) GetIoSize() uint32 {
	if x != nil {
		return x.IoSize
	}
	return 0
}

func (x *StatFs) GetInodes() uint64 {
	if x != nil {
		return x.Inodes
	}
	return 0
}

func (x *StatFs) GetInodesFree() uint64 {
	if x != nil {
		return x.InodesFree
	}
	return 0
}

type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Size    int64                  `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	Mode    uint32                 `protobuf:"varint,3,opt,name=Mode,proto3" json:"Mode,omitempty"`
	ModTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ModTime,proto3" json:"ModTime,omitempty"`
	IsDir   bool                   `protobuf:"varint,5,opt,name=IsDir,proto3" json:"IsDir,omitempty"`
	Ino     uint64                 `protobuf:"varint,6,opt,name=Ino,proto3" json:"Ino,omitempty"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{3}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfo) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

type OpenedDir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inode     uint64     `protobuf:"varint,1,opt,name=Inode,proto3" json:"Inode,omitempty"`
	Handle    uint64     `protobuf:"varint,2,opt,name=Handle,proto3" json:"Handle,omitempty"`
	OpContext *OpContext `protobuf:"bytes,3,opt,name=OpContext,proto3" json:"OpContext,omitempty"`
	CacheDir  bool       `protobuf:"varint,4,opt,name=CacheDir,proto3" json:"CacheDir,omitempty"`
	KeepCache bool       `protobuf:"varint,5,opt,name=KeepCache,proto3" json:"KeepCache,omitempty"`
}

func (x *OpenedDir) Reset() {
	*x = OpenedDir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenedDir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenedDir) ProtoMessage() {}

func (x *OpenedDir) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenedDir.ProtoReflect.Descriptor instead.
func (*OpenedDir) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{4}
}

func (x *OpenedDir) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *OpenedDir) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *OpenedDir) GetOpContext() *OpContext {
	if x != nil {
		return x.OpContext
	}
	return nil
}

func (x *OpenedDir) GetCacheDir() bool {
	if x != nil {
		return x.CacheDir
	}
	return false
}

func (x *OpenedDir) GetKeepCache() bool {
	if x != nil {
		return x.KeepCache
	}
	return false
}

type OpenedFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inode         uint64     `protobuf:"varint,1,opt,name=Inode,proto3" json:"Inode,omitempty"`
	Handle        uint64     `protobuf:"varint,2,opt,name=Handle,proto3" json:"Handle,omitempty"`
	KeepPageCache bool       `protobuf:"varint,3,opt,name=KeepPageCache,proto3" json:"KeepPageCache,omitempty"`
	UseDirectIO   bool       `protobuf:"varint,4,opt,name=UseDirectIO,proto3" json:"UseDirectIO,omitempty"`
	OpenFlags     uint32     `protobuf:"varint,5,opt,name=OpenFlags,proto3" json:"OpenFlags,omitempty"`
	OpContext     *OpContext `protobuf:"bytes,6,opt,name=OpContext,proto3" json:"OpContext,omitempty"`
}

func (x *OpenedFile) Reset() {
	*x = OpenedFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenedFile) ProtoMessage() {}

func (x *OpenedFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenedFile.ProtoReflect.Descriptor instead.
func (*OpenedFile) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{5}
}

func (x *OpenedFile) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *OpenedFile) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *OpenedFile) GetKeepPageCache() bool {
	if x != nil {
		return x.KeepPageCache
	}
	return false
}

func (x *OpenedFile) GetUseDirectIO() bool {
	if x != nil {
		return x.UseDirectIO
	}
	return false
}

func (x *OpenedFile) GetOpenFlags() uint32 {
	if x != nil {
		return x.OpenFlags
	}
	return 0
}

func (x *OpenedFile) GetOpContext() *OpContext {
	if x != nil {
		return x.OpContext
	}
	return nil
}

type DirEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IsDir    bool      `protobuf:"varint,2,opt,name=IsDir,proto3" json:"IsDir,omitempty"`
	FileMode uint32    `protobuf:"varint,3,opt,name=FileMode,proto3" json:"FileMode,omitempty"`
	Info     *FileInfo `protobuf:"bytes,4,opt,name=Info,proto3" json:"Info,omitempty"`
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{6}
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *DirEntry) GetFileMode() uint32 {
	if x != nil {
		return x.FileMode
	}
	return 0
}

func (x *DirEntry) GetInfo() *FileInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type FileEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inode     uint64     `protobuf:"varint,1,opt,name=Inode,proto3" json:"Inode,omitempty"`
	Handle    uint64     `protobuf:"varint,2,opt,name=Handle,proto3" json:"Handle,omitempty"`
	Offset    int64      `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Size      int64      `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	Dst       []byte     `protobuf:"bytes,5,opt,name=Dst,proto3" json:"Dst,omitempty"`
	Data      [][]byte   `protobuf:"bytes,6,rep,name=Data,proto3" json:"Data,omitempty"`
	BytesRead int32      `protobuf:"varint,7,opt,name=BytesRead,proto3" json:"BytesRead,omitempty"`
	OpContext *OpContext `protobuf:"bytes,8,opt,name=OpContext,proto3" json:"OpContext,omitempty"`
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{7}
}

func (x *FileEntry) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *FileEntry) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *FileEntry) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetDst() []byte {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *FileEntry) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileEntry) GetBytesRead() int32 {
	if x != nil {
		return x.BytesRead
	}
	return 0
}

func (x *FileEntry) GetOpContext() *OpContext {
	if x != nil {
		return x.OpContext
	}
	return nil
}

// Request Bodies
type StatFsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string      `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Context *RPCContext `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
}

func (x *StatFsReq) Reset() {
	*x = StatFsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatFsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFsReq) ProtoMessage() {}

func (x *StatFsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFsReq.ProtoReflect.Descriptor instead.
func (*StatFsReq) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{8}
}

func (x *StatFsReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatFsReq) GetContext() *RPCContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type FileInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string      `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Context *RPCContext `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
}

func (x *FileInfoReq) Reset() {
	*x = FileInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoReq) ProtoMessage() {}

func (x *FileInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoReq.ProtoReflect.Descriptor instead.
func (*FileInfoReq) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{9}
}

func (x *FileInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfoReq) GetContext() *RPCContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type OpenDirReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string      `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Context *RPCContext `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
}

func (x *OpenDirReq) Reset() {
	*x = OpenDirReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDirReq) ProtoMessage() {}

func (x *OpenDirReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDirReq.ProtoReflect.Descriptor instead.
func (*OpenDirReq) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{10}
}

func (x *OpenDirReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpenDirReq) GetContext() *RPCContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type OpenFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string      `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Context *RPCContext `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
}

func (x *OpenFileReq) Reset() {
	*x = OpenFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileReq) ProtoMessage() {}

func (x *OpenFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileReq.ProtoReflect.Descriptor instead.
func (*OpenFileReq) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{11}
}

func (x *OpenFileReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpenFileReq) GetContext() *RPCContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ReadDirReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string      `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Context *RPCContext `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
}

func (x *ReadDirReq) Reset() {
	*x = ReadDirReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirReq) ProtoMessage() {}

func (x *ReadDirReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirReq.ProtoReflect.Descriptor instead.
func (*ReadDirReq) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{12}
}

func (x *ReadDirReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadDirReq) GetContext() *RPCContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ReadFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string      `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Context *RPCContext `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
}

func (x *ReadFileReq) Reset() {
	*x = ReadFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileReq) ProtoMessage() {}

func (x *ReadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileReq.ProtoReflect.Descriptor instead.
func (*ReadFileReq) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{13}
}

func (x *ReadFileReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadFileReq) GetContext() *RPCContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// Response Bodies
type StatFsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *StatFs `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *StatFsRes) Reset() {
	*x = StatFsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatFsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFsRes) ProtoMessage() {}

func (x *StatFsRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFsRes.ProtoReflect.Descriptor instead.
func (*StatFsRes) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{14}
}

func (x *StatFsRes) GetResult() *StatFs {
	if x != nil {
		return x.Result
	}
	return nil
}

type FileInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *FileInfo `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *FileInfoRes) Reset() {
	*x = FileInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoRes) ProtoMessage() {}

func (x *FileInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoRes.ProtoReflect.Descriptor instead.
func (*FileInfoRes) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{15}
}

func (x *FileInfoRes) GetResult() *FileInfo {
	if x != nil {
		return x.Result
	}
	return nil
}

type OpenDirRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *OpenedDir `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *OpenDirRes) Reset() {
	*x = OpenDirRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDirRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDirRes) ProtoMessage() {}

func (x *OpenDirRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDirRes.ProtoReflect.Descriptor instead.
func (*OpenDirRes) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{16}
}

func (x *OpenDirRes) GetResult() *OpenedDir {
	if x != nil {
		return x.Result
	}
	return nil
}

type OpenFileRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *OpenedFile `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *OpenFileRes) Reset() {
	*x = OpenFileRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenFileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileRes) ProtoMessage() {}

func (x *OpenFileRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileRes.ProtoReflect.Descriptor instead.
func (*OpenFileRes) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{17}
}

func (x *OpenFileRes) GetResult() *OpenedFile {
	if x != nil {
		return x.Result
	}
	return nil
}

type ReadDirRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*DirEntry `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty"`
}

func (x *ReadDirRes) Reset() {
	*x = ReadDirRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDirRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirRes) ProtoMessage() {}

func (x *ReadDirRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirRes.ProtoReflect.Descriptor instead.
func (*ReadDirRes) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{18}
}

func (x *ReadDirRes) GetResult() []*DirEntry {
	if x != nil {
		return x.Result
	}
	return nil
}

type ReadFileRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *FileEntry `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *ReadFileRes) Reset() {
	*x = ReadFileRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcfs_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRes) ProtoMessage() {}

func (x *ReadFileRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcfs_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRes.ProtoReflect.Descriptor instead.
func (*ReadFileRes) Descriptor() ([]byte, []int) {
	return file_proto_grpcfs_proto_rawDescGZIP(), []int{19}
}

func (x *ReadFileRes) GetResult() *FileEntry {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proto_grpcfs_proto protoreflect.FileDescriptor

var file_proto_grpcfs_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x66, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x0a, 0x52, 0x50, 0x43,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x47, 0x0a, 0x09, 0x4f, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x46, 0x75, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x46, 0x75, 0x73, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x50, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x55, 0x69, 0x64, 0x22, 0xd8, 0x01, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x46, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x46, 0x72, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x46, 0x72, 0x65, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6f, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x49, 0x6f, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x49,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x46,
	0x72, 0x65, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x49, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x46, 0x72, 0x65, 0x65, 0x22, 0xa4, 0x01, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x34,
	0x0a, 0x07, 0x4d, 0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x4d, 0x6f, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x44, 0x69, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x49, 0x73, 0x44, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x6e,
	0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x49, 0x6e, 0x6f, 0x22, 0xa0, 0x01, 0x0a,
	0x09, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x44, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x49, 0x6e, 0x6f, 0x64, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x4f, 0x70, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x4f, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x09, 0x4f, 0x70, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x69,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x69,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x4b, 0x65, 0x65, 0x70, 0x43, 0x61, 0x63, 0x68, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x4b, 0x65, 0x65, 0x70, 0x43, 0x61, 0x63, 0x68, 0x65, 0x22,
	0xcd, 0x01, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x49,
	0x6e, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x0d,
	0x4b, 0x65, 0x65, 0x70, 0x50, 0x61, 0x67, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0d, 0x4b, 0x65, 0x65, 0x70, 0x50, 0x61, 0x67, 0x65, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x49,
	0x4f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x55, 0x73, 0x65, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x49, 0x4f, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x6c, 0x61, 0x67,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x6c, 0x61,
	0x67, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x4f, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x52, 0x09, 0x4f, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22,
	0x72, 0x0a, 0x08, 0x44, 0x69, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x49, 0x73, 0x44, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x49, 0x73, 0x44, 0x69, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x12, 0x20, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0xd6, 0x01, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x44,
	0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x44, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x61, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x61, 0x64, 0x12,
	0x2b, 0x0a, 0x09, 0x4f, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x52, 0x09, 0x4f, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x49, 0x0a, 0x09,
	0x53, 0x74, 0x61, 0x74, 0x46, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x50, 0x43, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x4b, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x50, 0x43, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x4a, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x69, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x50, 0x43,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x22, 0x4b, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x50, 0x43, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x4a, 0x0a,
	0x0a, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x28, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x50, 0x43, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x4b, 0x0a, 0x0b, 0x52, 0x65, 0x61,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x50, 0x43, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x2f, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x46, 0x73,
	0x52, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x46, 0x73, 0x52,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x33, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x33, 0x0a, 0x0a,
	0x4f, 0x70, 0x65, 0x6e, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x44, 0x69, 0x72, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x35, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x12, 0x26, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x32, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64,
	0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x72, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x34, 0x0a, 0x0b,
	0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x32, 0xa1, 0x02, 0x0a, 0x0b, 0x46, 0x75, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x46, 0x73, 0x12, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x46, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x46, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x07,
	0x4f, 0x70, 0x65, 0x6e, 0x44, 0x69, 0x72, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65,
	0x6e, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65,
	0x6e, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x08, 0x4f, 0x70, 0x65,
	0x6e, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65, 0x6e,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x07, 0x52, 0x65, 0x61,
	0x64, 0x44, 0x69, 0x72, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69,
	0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x67, 0x72, 0x70, 0x63, 0x66, 0x73,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_grpcfs_proto_rawDescOnce sync.Once
	file_proto_grpcfs_proto_rawDescData = file_proto_grpcfs_proto_rawDesc
)

func file_proto_grpcfs_proto_rawDescGZIP() []byte {
	file_proto_grpcfs_proto_rawDescOnce.Do(func() {
		file_proto_grpcfs_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_grpcfs_proto_rawDescData)
	})
	return file_proto_grpcfs_proto_rawDescData
}

var file_proto_grpcfs_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_grpcfs_proto_goTypes = []any{
	(*RPCContext)(nil),            // 0: pb.RPCContext
	(*OpContext)(nil),             // 1: pb.OpContext
	(*StatFs)(nil),                // 2: pb.StatFs
	(*FileInfo)(nil),              // 3: pb.FileInfo
	(*OpenedDir)(nil),             // 4: pb.OpenedDir
	(*OpenedFile)(nil),            // 5: pb.OpenedFile
	(*DirEntry)(nil),              // 6: pb.DirEntry
	(*FileEntry)(nil),             // 7: pb.FileEntry
	(*StatFsReq)(nil),             // 8: pb.StatFsReq
	(*FileInfoReq)(nil),           // 9: pb.FileInfoReq
	(*OpenDirReq)(nil),            // 10: pb.OpenDirReq
	(*OpenFileReq)(nil),           // 11: pb.OpenFileReq
	(*ReadDirReq)(nil),            // 12: pb.ReadDirReq
	(*ReadFileReq)(nil),           // 13: pb.ReadFileReq
	(*StatFsRes)(nil),             // 14: pb.StatFsRes
	(*FileInfoRes)(nil),           // 15: pb.FileInfoRes
	(*OpenDirRes)(nil),            // 16: pb.OpenDirRes
	(*OpenFileRes)(nil),           // 17: pb.OpenFileRes
	(*ReadDirRes)(nil),            // 18: pb.ReadDirRes
	(*ReadFileRes)(nil),           // 19: pb.ReadFileRes
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_proto_grpcfs_proto_depIdxs = []int32{
	20, // 0: pb.FileInfo.ModTime:type_name -> google.protobuf.Timestamp
	1,  // 1: pb.OpenedDir.OpContext:type_name -> pb.OpContext
	1,  // 2: pb.OpenedFile.OpContext:type_name -> pb.OpContext
	3,  // 3: pb.DirEntry.Info:type_name -> pb.FileInfo
	1,  // 4: pb.FileEntry.OpContext:type_name -> pb.OpContext
	0,  // 5: pb.StatFsReq.Context:type_name -> pb.RPCContext
	0,  // 6: pb.FileInfoReq.Context:type_name -> pb.RPCContext
	0,  // 7: pb.OpenDirReq.Context:type_name -> pb.RPCContext
	0,  // 8: pb.OpenFileReq.Context:type_name -> pb.RPCContext
	0,  // 9: pb.ReadDirReq.Context:type_name -> pb.RPCContext
	0,  // 10: pb.ReadFileReq.Context:type_name -> pb.RPCContext
	2,  // 11: pb.StatFsRes.Result:type_name -> pb.StatFs
	3,  // 12: pb.FileInfoRes.Result:type_name -> pb.FileInfo
	4,  // 13: pb.OpenDirRes.Result:type_name -> pb.OpenedDir
	5,  // 14: pb.OpenFileRes.Result:type_name -> pb.OpenedFile
	6,  // 15: pb.ReadDirRes.Result:type_name -> pb.DirEntry
	7,  // 16: pb.ReadFileRes.Result:type_name -> pb.FileEntry
	8,  // 17: pb.FuseService.StatFs:input_type -> pb.StatFsReq
	9,  // 18: pb.FuseService.FileInfo:input_type -> pb.FileInfoReq
	10, // 19: pb.FuseService.OpenDir:input_type -> pb.OpenDirReq
	11, // 20: pb.FuseService.OpenFile:input_type -> pb.OpenFileReq
	12, // 21: pb.FuseService.ReadDir:input_type -> pb.ReadDirReq
	13, // 22: pb.FuseService.ReadFile:input_type -> pb.ReadFileReq
	14, // 23: pb.FuseService.StatFs:output_type -> pb.StatFsRes
	15, // 24: pb.FuseService.FileInfo:output_type -> pb.FileInfoRes
	16, // 25: pb.FuseService.OpenDir:output_type -> pb.OpenDirRes
	17, // 26: pb.FuseService.OpenFile:output_type -> pb.OpenFileRes
	18, // 27: pb.FuseService.ReadDir:output_type -> pb.ReadDirRes
	19, // 28: pb.FuseService.ReadFile:output_type -> pb.ReadFileRes
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_grpcfs_proto_init() }
func file_proto_grpcfs_proto_init() {
	if File_proto_grpcfs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_grpcfs_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RPCContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*OpContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*StatFs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*OpenedDir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*OpenedFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DirEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*FileEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*StatFsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*FileInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*OpenDirReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*OpenFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*ReadDirReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*ReadFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*StatFsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*FileInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*OpenDirRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*OpenFileRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*ReadDirRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcfs_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*ReadFileRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_grpcfs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grpcfs_proto_goTypes,
		DependencyIndexes: file_proto_grpcfs_proto_depIdxs,
		MessageInfos:      file_proto_grpcfs_proto_msgTypes,
	}.Build()
	File_proto_grpcfs_proto = out.File
	file_proto_grpcfs_proto_rawDesc = nil
	file_proto_grpcfs_proto_goTypes = nil
	file_proto_grpcfs_proto_depIdxs = nil
}
